# Generated by Django 3.1 on 2020-11-15 17:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_assignment_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='time',
        ),
        migrations.AddField(
            model_name='assignment',
            name='date_and_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 15, 17, 43, 32, 684105, tzinfo=utc)),
        ),
    ]
