# Generated by Django 3.1 on 2020-11-27 19:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_auto_20201115_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='breakfast',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='date_and_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 27, 19, 42, 11, 819805, tzinfo=utc)),
        ),
    ]
