# Generated by Django 3.1 on 2020-11-28 10:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_auto_20201127_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='date_and_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 28, 10, 53, 52, 671167, tzinfo=utc)),
        ),
    ]
